spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.238:3306/ibn_rms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  web:
    resources:
      static-locations: classpath:/templates/
mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true

